# Generated by Django 3.2.8 on 2021-10-24 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211023_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satimage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='satimage',
            name='created_on',
        ),
    ]
