# Generated by Django 3.2.8 on 2021-12-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_satimage_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satimage',
            name='action',
            field=models.CharField(choices=[('0', 'Roads'), ('1', 'Planes'), ('2', 'Buildings')], default=0, max_length=11),
        ),
    ]
